MAX_TIME: 200000
n_wafer: 75
time_coef_penalty: 10
warn_coef_penalty: 4
transport_overtime_coef_penalty: 6.0
processing_coef_reward: 5.0
in_system_time_penalty_coef: 0.0
done_event_reward: 500
scrap_event_penalty: 4000
wait_durations:
  - 5
cleaning_enabled: false
stride: true
single_route_config_path: route_config.json
single_route_name: "4-8"
dual_arm: true
