MAX_TIME: 4000
n_wafer1: 13
n_wafer2: 0
time_coef_penalty: 11
warn_coef_penalty: 0.5
transport_overtime_coef_penalty: 6.0
processing_coef_reward: 5.0
in_system_time_penalty_coef: 0.0
done_event_reward: 500
scrap_event_penalty: 4000
wait_durations:
  - 5
max_wafers1_in_system: 16
max_wafers2_in_system: 6
cleaning_enabled: true
single_route_config_path: cascade_routes_1_star.json
single_route_name: "2-1"
dual_arm: true
